service: sls-base

custom:
  region: ${file(./env.yml):${opt:stage, 'dev'}.region}
  AuctionsTable: AuctionsTable-${opt:stage, 'dev'}

provider:
  name: aws
  runtime: nodejs18.x
  region: ${self:custom.region}
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  environment:
    AUCTIONS_TABLE_NAME: ${self:custom.AuctionsTable}
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - ${file(iam/AuctionsTableIAM.yml):AuctionsTableIAM}

resources:
  Resources:
    AuctionsTable: ${file(resources/AuctionsTable.yml):AuctionsTable}

functions:
  createAuction:
    handler: src/handler.createAuction
    events:
      - http:
          method: POST
          path: /auction
  
  getAuctions:
    handler: src/handler.getAuctions
    events:
      - http:
          method: GET
          path: /auctions

package:
  individually: true
